'use client'

import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import getConfig from 'next/config'
import Image from 'next/image'

import profilePic from '../../public/images/profile/developer-pic.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import LcdComponent from '@/components/LcdComponent'
import Transition from '@/components/Transition'
import Envelope from '@/components/Envelope'

const inter = Inter({ subsets: ['latin'] })

const Home = () => {




  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transition />
      <main className='dark:text-light'>
        <Layout className='h-auto md:p-12 sm:p-6  lg:p-32 pb-10'>
          <div className="flex items-center  justify-between w-full lg:flex-col lg:h-full">
            <div className='w-1/2  flex items-center justify-center md:w-full'>
              <Image src={profilePic} alt="Profile Picture"
                className=' dark:grayscale dark:opacity-80 lg:max-w[100%] hover:dark:grayscale-0 transition-all
                 duration-500 lg:grayscale-0 lg:dark:grayscale-0 lg:hidden md:inline-block md:w-full '
                // setting priority true makes it more optimized and preloads that save loading time
                // and good score in testing library
                priority sizes="(max-width: 768px) 40vw, (max-width: 1200px) 50vw, 30vw" />
            </div>

            <div className='w-1/2 flex flex-col  items-center self-center lg:w-full lg: text-center'>
              <AnimatedText
                className='inline-block w-full text-primary dark:text-primaryDark font-bold capitalize 
                !text-6xl !text-left xl:!text-6xl lg:!text-5xl lg:!text-center md:!text-4xl sm:!text-2xl'
                text="Converting Ideas into Digital Realities Through Code and Design"

              />
              <p className='my-4  font-medium md:text-sm xm:text-xs'>
                As a proficient Software Engineer, my dedication centers around bringing concepts to life as cutting-edge
                web applications. You&#39;re invited to explore my recent projects and articles, which serve as tangible
                demonstrations of my mastery in the field of front-end web development.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center' >
                <Link href='/resume_pdf.pdf'
                  target={'_blank'}
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg
                   text-lg font-semibold hover:bg-light
                  hover:text-primary dark:text-dark border border-solid border-transparent hover:border-dark 
                  dark:hover:text-primaryDark dark:bg-light  dark:hover:bg-dark dark:border-light
                  md:p-2 md:px-4 md:text-base' download={true} >
                  Resume
                  <LinkArrow className={'ml-1 w-6'} />
                </Link>
                <Link href="mailto:mazher.nazeer@gmail.com" target={'_blank'}
                  className='ml-4 font-medium text-lg capitalize text-primary dark:text-primaryDark underline  md:text-base'>
                  Email Me
                </Link>
              </div>
            </div>
          </div>

          <LcdComponent className="mt-28 mb-10 lg:mt-14 lg:mb-8 " />

          <Envelope />
        </Layout>
      </main>
    </>
  )
}
export default Home